config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/posts', to: 'posts#index'
  root 'posts#index'

  resources :users, only: [:show, :edit, :update, :all] do
    resources :posts do
      resources :comments
    end
    resources :followers, only: :index
    resources :followings, only: :index
    resource :admin, only: [:create, :destroy]
  end

  resources :follows, only: [:create, :destroy]

  #, only: [:new, :create, :index, :edit, :update, :show, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true, length: { maximum: 130}
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :following, class_name: "User", foreign_key: "following_id"
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image) # adds an `image` virtual attribute

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :content, presence: true, length: { maximum: 500}
  validates :image_data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
 EMAIL_FORMAT = /[^@]+@[^\.]+\..+/

 devise :database_authenticatable, :registerable

 has_many :posts, dependent: :destroy
 has_many :comments, dependent: :destroy

 has_many :followers, through: :follower_follows, source: :follower
 has_many :follower_follows, foreign_key: :following_id, class_name: "Follow"

 has_many :followings, through: :following_follows, source: :follower
 has_many :following_follows, foreign_key: :follower_id, class_name: "Follow"

 validates :email, presence: true, uniqueness: true
 validates :email, format: { with: EMAIL_FORMAT}
 validates :name, presence: true
 validates :bio, presence: true

 private

 def admin?
  admin
 end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def create
    @user = User.find(params[:id])
    @user.update(admin: true)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(admin: false)
    redirect_to @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Devise::Controllers::Helpers
  # protect_from_forgery with: :exception
  #
  # def after_sign_in_path_for(user)
  #   user_posts_path(user)
  # end
  # before_action :configure_permitted_parameters
  before_action :configure_permitted_parameters, if: :devise_controller?



  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :bio])
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path
    end
  end

  def load_user
    @user ||= params[:user_id].present? ? User.find(params[:user_id]) : current_user
  end

  # def load_user
  #   @user = User.find(params[:user_id])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to request.referrer
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

end

app/controllers/followers_controller.rb
class FollowersController
  def index
    @user = User.find(params[:id])
    @followers = @user.followers
  end
end

app/controllers/followings_controller.rb
class FollowingsController
  def index
    @user = User.find(params[:id])
    @followings = @user.followings
  end
end

app/controllers/follows_controller.rb
class FollowsController
  before_action :authenticate_user!

  def create
    follower_user = current_user
    following_user = User.find(params[:following_id])

    Follow.create(follower: :follower_user, following: :following_user)

    redirect_to user_followers_path(current_user)
  end

  def destroy
    follower_user = current_user
    following_user = User.find(params[:following_id])

    follow = Follow.find(follower: :follower_user, following: :following_user)
    follow.destroy

    redirect_to user_followers_path(current_user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user

  def index
    @posts = Post.order(created_at: :desc)
    # @posts = @user.posts
    # @posts = Post.all
    # @posts = Post.all.map { |post| "#{post.title} #{post.content}"}.join("\n")
    # render plain: @posts
  end

  def show
    @post = @user.posts.find(params[:id])
    # @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # @post.user = @user
    @user = @post.user
    if @post.save
      redirect_to user_post_path(@user, @post), flash: { success: "Post was created" }
    else
      render :new, flash: { alert: "Some error occured"}
    end
  end

  def edit
    @post = @user.posts.find(params[:id])
  end

  def update
    @post = @user.posts.find(params[:id])
    # @post.user = @user
    @user = @post.user
    if @post.update(post_params)
      redirect_to user_post_path(@user, @post), flash: { success: "Post was updated" }
    else
      render 'edit'
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    @post.destroy
    redirect_to action: :index
    # redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image, :user_id)
  #  TODO: later add another filters such as likes, images etc.
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_update_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_update_params
    params.require(:user).permit(:name, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<!-- Single Comment -->
<div class="media mb-4">
  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
  <div class="media-body">
    <h5 class="mt-0"> by <%= link_to @user.name, '#'  %></h5>
    <%= comment.content %>
  </div>
  <%= link_to "Delete", [@user, comment.post, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
</div>

app/views/comments/_form.html.erb
<!-- Comments Form -->
<h5 class="card-header">Leave a Comment:</h5>
<div class="card-body">
  <%= simple_form_for([@user, post, post.comments.build]) do |f| %>
    <%= f.input :content %>
    <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/followers/index.html.erb
<div class="card my-4">
  <h1>Followers:</h1>
  <ul>
    <% @followers.each do |follower| %>
    <li>
      <%= link_to(follower.name, user_path(follower)) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/followings/index.html.erb
<div class="card my-4">
  <h1>Followings:</h1>

  <ul>
    <% @followings.each do |following| %>
      <li>
        <%= link_to(following.name, user_path(following)) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <span class="navbar-brand"><%= link_to 'InstaClone', root_path, class: "navbar-brand "%></span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item active">
              <span class="nav-link"><%= link_to 'Home', root_path, class: "nav-link" %></span>
            </li>
              <li class="nav-item active">
                <span class="nav-link"><%= link_to 'Explore', root_path, class: "nav-link" %></span>
              </li>
            <li class="nav-item">
              <span class="nav-link"><%= link_to 'New post', new_user_post_path(@user), class: "nav-link" %></span>
            </li>
            <li class="nav-item">
              <span class="nav-link"><%= link_to 'Profile', user_path(@user), class: "nav-link" %></span>
            </li>
            <li class="nav-item">
              <span class="nav-link">
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
               </span>
                <% else %>
              <span class="nav-link">
                  <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
              </span>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">

        <div class="col-lg-8">
          <%= yield %>
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                    <li>
                      <span><%= link_to 'Link', root_path %></span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; NickS</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card my-4">
  <h5 class="card-header"><%= yield :page_title %></h5>
  <div class="card-body">
    <%= simple_form_for [@user, @post] do |f| %>
      <%= f.input :title %>
      <%= f.input :image, as: :hidden, input_html: { value: @post.cached_image_data } %>
      <%= f.input :image, as: :file %>
      <%= f.input :content %>
      <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.erb
<div class="card my-4">
  <!-- Author, Title-->
  <p class="lead card-header">
    by
    <%= link_to @user.name, '#'  %>
<!--    <a href="#">Author!!!!!!!!</a>-->
    <%#= link_to post.title, post %>
    <span><%= post.title %></span>
    <%#= post.id %>
  </p>

  <!-- Preview Image -->
  <%= link_to (image_tag post.image_url, class: "img-fluid rounded"), user_post_path(@user, post) %>

  <div class="card-header">
    <!-- Post Content -->
    <p class="lead"><%= post.content %></p>
    <!-- Date/Time -->
    <p class="mt-0"><%= post.updated_at %></p>

    <button class="" type="button"><svg aria-label="Like" class="" fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg></button>
    <button class="" type="button"><svg aria-label="Unlike" class="" fill="#ed4956" height="24" viewBox="0 0 48 48" width="24"><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg></button>

    <div class="btn-toolbar justify-content-between" >
      <%= link_to "Edit", edit_user_post_path(@user, post), class: "btn btn-primary" %>
      <%= link_to "Delete", user_post_path(@user, post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </div>

  <!-- Single Comment -->
  <%= render post.comments %>
<!--  <hr>-->
  <!-- Comments Form -->
  <%= render 'comments/form', post: post %>
</div>

app/views/posts/edit.erb
<%= content_for :page_title, 'Edit post:' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<!-- Post Content Column -->
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= content_for :page_title, 'New post:' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

app/views/users/_manage.html.erb
<% if current_user.admin? %>
<h1>User management</h1>

<h2>Admin status</h2>

<div class="card-header">
  <div class="btn-toolbar justify-content-between" >
    <% if user.admin? %>
      <%= link_to "Demote", user_admin_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Promote to admin", user_admin_path(user), method: :put, class: "btn btn-primary" %>
     <% end %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="card my-4">
  <h5 class="card-header"><%= yield :name %></h5>
  <div class="card-body">
    <%= simple_form_for [@user] do |f| %>
      <%= f.input :name %>
<!--      TODO: add avatar -->
      <%#= f.input :image, as: :hidden, input_html: { value: @post.cached_image_data } %>
      <%#= f.input :image, as: :file %>
      <%= f.input :bio %>
      <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card my-4">
<h1><%= @user.name %> Info:</h1>
  Email: <%= @user.email %>
  <br>
  Name: <%= @user.name %>
  <br>
  Bio: <%= @user.bio %>
  <br>
  <%= link_to("Edit Profile", edit_user_path(@user)) %>
  <br>
  <%= link_to("Posts", user_posts_path(@user)) %>
</div>